a=int(input("Enter the first  number:"))
b=int(input("Enter the second number:"))
c=float(a)/float(b)
print("Addition:",a+b)
print("Substraction:",a-b)
print("Multiplication:",a*b)
print("Division:",c)